version: '3'
services:
  mvn:
    build:
      context: ./images
      dockerfile: Dockerfile
    volumes:
    - /webapp/:/tmp/boxfuse-sample-java-war-hello/target
  webapp:
    build:
      context: ./images
      dockerfile: Dockerfile-tomcat
    volumes:
    - /webapp/:/opt/tomcat/apache-tomcat-8.5.60/webapps/
