
version: '3'
services:
  mvn:
    build:
       context: ./images
       dockerfile: Dockerfile
    volumes:
     - type: volume
       source: webapp
       target: /tmp/boxfuse-sample-java-war-hello/target/
  webapp:
    build:
       context: ./images
       dockerfile: Dockerfile-tomcat
    ports:
       - "8080:8080"
    volumes:
     - type: volume
       source: ./webapp
       target: /opt/tomcat/apache-tomcat-8.5.60/webapps/
       volume:
         nocopy: true
volumes:
  webapp: